---
mentionMe: <@430905454961623060>
commands:
  - name: help
    mentionRequired: true
    cmds:
      - help
    response: |
      **Welcome to Sprinty McSprintFace!**

      First up: typing '<@430905454961623060> help' or 'help <@430905454961623060>' will make this goofy bot try to help you!

      Note, for spam reasons, Sprinty will only reply to you in a DM! Please DM Sprinty directly instead of spamming a busy channel!
