---
commands:
  - name: help
    cmds:
      - <@430905454961623060> help
    response: |
      **Welcome to Sprinty McSprintFace!**

      First up: typing 'help' will make this goofy bot try to help you!
